apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: secret-agent-java  
  labels:
    app.kubernetes.io/part-of: secret-agent-java
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: secret-agent-java
spec:
  template:
    metadata:
      annotations:                
        autoscaling.knative.dev/minScale: "1"
        services.conventions.carto.run/postgres: postgresql/42.3.7
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: secret-agent-java
        carto.run/workload-name: secret-agent-java        
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details="always" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include="*" -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: akseutap5registry.azurecr.io/library/tanzu-supply-chain/secret-agent-java-secret-agent@sha256:ccfa29f44d00e703539a2d36dda923066d8046dc9732e608a25e5485cb04197b
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

