apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: secret-agent-java
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: secret-agent-java
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: scanning_source_policy
      value: scan-policy-java
    - name: scanning_image_policy
      value: scan-policy-java
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  #serviceClaims:
  #  - name: postgres-db
  #    ref:
  #      apiVersion: sql.tanzu.vmware.com/v1
  #      kind: Postgres
  #      name: kcd-fr-23-database
  #env:
  #  - name: SPRING_PROFILES_ACTIVE
  #    value: postgres
