apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sb-nodejs-demo-1     
spec:
  template: 
    spec:
      containers:
      - name: workload
        image: my-app:v1
        securityContext:
          runAsUser: 1001
      




