apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: micropets-secrets
spec:  
  inputResources:
    - name: server
      ref:
        apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
        kind: FlexibleServer
        name: micropetsdb-psql-srv
    - name: db
      ref:
        apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
        kind: FlexibleServersDatabase
        name: micropetsdb-psql
    - name: creds
      ref:
        apiVersion: v1
        kind: Secret
        name: "$(.server.spec.administratorLoginPassword.name)"
  template:
    type: postgresql
    stringData:
      type: postgresql
      port: "5432"
      database: "$(.db.status.name)"
      host: "$(.server.status.fullyQualifiedDomainName)"
      username: "$(.server.status.administratorLogin)"
    data:
      password: "$(.creds.data.password)"
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: custom-user-password
spec:
  length: 27    
  digits: 2
  uppercaseLetters: 4
  lowercaseLetters: 10
  symbols: 3  
