apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sb-nodejs-demo-3
  labels:
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sb-nodejs-demo    
    app.kubernetes.io/component: run    
spec:
  template:
    metadata:
      annotations:        
        autoscaling.knative.dev/minScale: "1"        
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/part-of: sb-nodejs-demo        
    spec:
      containers:
      - image: akseutap5registry.azurecr.io/library/tanzu-supply-chain/sb-nodejs-demo-secret-agent@sha256:4df5ea70ba337f1d37a38557e2cb31b87b5bb48647960ea641e65f2537c90d42
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1001
      serviceAccountName: default

