apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sb-nodejs-demo
  name: sb-nodejs-demo-bindings
spec:
  name: app-config
  service:
    apiVersion: v1
    kind: Secret
    name: configuration-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: sb-nodejs-demo-1
