apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sb-nodejs-demo
  name: sb-nodejs-demo-bindings
spec:
  name: app-config
  env:
    - key: A_TITLE
      name: BENOIT_TITLE
    - key: A_ENV
      name: BENOIT_ENV
  service:
    apiVersion: v1
    kind: Secret
    name: configuration-3
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    selector:
      matchLabels:
        app.kubernetes.io/part-of: sb-nodejs-demo
      
