apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sb-nodejs-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sb-nodejs-demo
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: scanning_source_policy
      value: scan-policy-nodejs-mongodb
    - name: scanning_image_policy
      value: scan-policy-nodejs-mongodb
    - name: userId
      value: 1001
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
